pilot:
  autoscaleEnabled: false
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

global:
  proxy:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
