apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
resources:
  - namespace.yaml
  - gateway.yaml
  - catalog.yaml
  - inventory.yaml
  - orders.yaml
  - payments.yaml
  - network-policies.yaml
